### PR TITLE
QuickSort

### PR DESCRIPTION
**Pull request by charu27**
Hello
I am Charu Sehgal from National Institute of technology Hamirpur and I have proposed this code for Quick sort which is in python language

### CODE REVIEW

**Review by shwetagurnani — CHANGES_REQUESTED** [review]
Following the contribution guidelines of this repository, please create a folder with the name quick_sort and put this code file inside it. Thanks!

**Comment by charu27** [comment]
okk

**Comment by charu27** [comment]
Changes done.

**Review by shwetagurnani — APPROVED** [review]

**Comment by shwetagurnani** [comment]
Thank you for your contribution.

**Pull request merged**
