### PR TITLE
Create Fenwick.cpp

### PR DESCRIPTION
**Pull request by kewlaninaveen5**

### CODE REVIEW

**Review by shwetagurnani — COMMENTED** [review]
Please rename the folder as fenwick_tree and file as fenwick_tree.cpp

**Comment by kewlaninaveen5** [comment]
File name renamed

**Review by shwetagurnani — CHANGES_REQUESTED** [review]
Following the contribution guidelines of the repository, please rename file name as fenwick_tree.cpp

**Comment by kewlaninaveen5** [comment]
Renamed

**Review by shwetagurnani — APPROVED** [review]

**Comment by shwetagurnani** [comment]
Thank you for your contribution!

**Pull request merged**
