### PR TITLE
Create LowestCommonAncestor.cpp

### PR DESCRIPTION
**Pull request by kewlaninaveen5**

### CODE REVIEW

**Review by shwetagurnani — COMMENTED** [review]
Please rename the folder as lowest_common_ancestor and the file name as lowest_common_ancestor.cpp

**Comment by kewlaninaveen5** [comment]
File Renamed

**Review by shwetagurnani — CHANGES_REQUESTED** [review]
Following the contribution guidelines of the repository, Please rename the file name as lowest_common_ancestor.cpp

**Comment by kewlaninaveen5** [comment]
Renamed

**Comment by shwetagurnani** [comment]
Thank you for your contribution!

**Pull request merged**
